#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the matchingStrings function below.
def matchingStrings(strings, queries):
    
    #Method 1: Using 2 for loops. Complexity: O(nm), n=String length, m=Query length
    countQuery = [0]*len(queries)
    for query in range(len(queries)):
        for ele in strings:
            if queries[query] == ele:
                countQuery[query]+=1
    return countQuery

    #Method 2: Using 1 for loop at a time. Complexity: O(n), n=String length
    dictQueries = {}
    for query in queries:
        dictQueries[query] = 0 
    for ele in strings:
        if ele in dictQueries.keys():
            dictQueries[ele]+=1
    return dictQueries
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    strings_count = int(input())

    strings = []

    for _ in range(strings_count):
        strings_item = input()
        strings.append(strings_item)

    queries_count = int(input())

    queries = []

    for _ in range(queries_count):
        queries_item = input()
        queries.append(queries_item)

    res = matchingStrings(strings, queries)

    fptr.write('\n'.join(map(str, res)))
    fptr.write('\n')

    fptr.close()
